[package]
name = "intention_tester"
version = "0.1.0"
authors = ["JBGriesner <jb.griesner@qwant.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
log = "0.4"
failure = "0.1"
csv = "1"
serde = "1"
serde_derive = "1"
hyper = "0.12"
reqwest = "*"
serde_json = "1.0"
rusty-machine="0.5.4"
